### ISSUE TITLE
Home link directs to https://www.cloud.service.gov.uk

### ISSUE THREAD

**Issue by Rory80Hz** [alphagov/paas-tech-docs#2]
https://paas-tech-docs.cloudapps.digital/

Currently the hyperlink  "GOV.UK  Platform as a Service BETA " (beside the crown logo) routes to https://www.cloud.service.gov.uk which returns a 404 error.

I will create a pull request to point to: https://govuk-paas.cloudapps.digital/ if the above URL isn't going to be in place for some time.

**Comment by bleach** [comment]
Hi @Rory80Hz,

Thanks for the report.

We're working on making www.cloud.service.gov.uk available at the moment, so it should be in place before we switch over to these new docs.

Cheers,
Graham

**Comment by Rory80Hz** [comment]
Awesome. Thought that might be the case 👍

**Comment by mtekel** [comment]
The docs are now available at www.cloud.service.gov.uk, so no need to change the link any more, resolving.
