### ISSUE TITLE
Issue with Travis documentation

### ISSUE THREAD

**Issue by simonneb** [alphagov/paas-tech-docs#304]
The ["Using the Travis CI tool"](https://github.com/alphagov/paas-tech-docs/blob/master/source/documentation/using_ci/travis.md) page contains an error. 

The `gem install travis --no-rdoc --no-ri` function has been depreciated and replaced with `gem install travis --no-document`.

Tested new method and it works. Need to then manually create empty .travis.yml file

**Comment by kr8n3r** [comment]
Hi, we have now removed this page from the documentation, so will close this issue.
Thank you for taking the time to report it in the first place
