### ISSUE TITLE
Add a page for the roadmap

### ISSUE THREAD

**Issue by matthewford** [alphagov/paas-tech-docs#312]

**Comment by pauldougan** [comment]
Hi Matt, our canonical roadmap page is at https://www.cloud.service.gov.uk/roadmap which essentially signposts the way to the platform roadmap from the product pages.

I agree there should be a route to the roadmap from the technical documention, given that at the moment a search for roadmap does not yield any hits.

As a use of our technical documentation where do you think the links to the roadmap should live that would make sense to you?

**Comment by matthewford** [comment]
@pauldougan fair enough, perhaps a mention on this page, https://docs.cloud.service.gov.uk/#gov-uk-platform-as-a-service would be useful.
